[project]
name = "fastapi_uploadstream"
version = "0.0.1"
description = "3rd party extension for streaming uploads in FastAPI"
license = 'MIT'
readme = "README.md"
authors = [{ name = "whichoneiwonder", email = "whichoneiwonder@github.com" }]
requires-python = ">=3.10"
dependencies = [
    "anyio>=3.6.2,<5",
    "fastapi>=0.116.1",
    "starlette>=0.49.1",
    "typing-extensions>=4.14.1; python_version < '3.11'",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Internet :: WWW/HTTP",
    "Framework :: FastAPI",
    "Framework :: AnyIO",
]
keywords = [
    "fastapi",
    "upload",
    "streaming",
    "http",
    "asynchronous",
]
[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.1",
    "python-multipart>=0.0.28",
    "ruff>=0.12.7",
    "trio>=0.33.0",
]
standard = [
    "fastapi[standard]>=0.116.1",
]

[tool.ruff]
line-length = 120
lint.select = [
    "E",
    "F",
    "W",
    "C90",
    "B",
    "B9",
    "I",
    "Q",
    "S",
    "T",
    "ERA",
    "ANN",
    "FAST",
    "RUF",
]
lint.per-file-ignores = { "tests/**.py" = ["S101"] }
